### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/Markdown-Cheatsheet#5]
![License](https://img.shields.io/badge/license-MIT-blue.svg)

**Comment by Kernix13** [comment]
Do you want me to add badges? I was thinking of doing forks and issues for this repo. They used to have a badge for GitHub stars but I can't find it now:

Forks:

```md
![GitHub forks](https://img.shields.io/github/forks/lifeparticle/Markdown-Cheatsheet?style=for-the-badge)
```

![GitHub forks](https://img.shields.io/github/forks/lifeparticle/Markdown-Cheatsheet?style=for-the-badge)

Open Issues:

```md
![GitHub issues](https://img.shields.io/github/issues/lifeparticle/Markdown-Cheatsheet?style=for-the-badge)
```

![GitHub issues](https://img.shields.io/github/issues/lifeparticle/Markdown-Cheatsheet?style=for-the-badge)

Let me know if you want me to create a brance for these and where you want them. I would think it would be best to add it after the title

**Comment by lifeparticle** [comment]
Hi, yes please that would be great. Can we add it after the **Images** section? Thank you! Looks really good.

**Comment by Kernix13** [comment]
Both of them or just one as an example?

**Comment by lifeparticle** [comment]
One is fine, thank you.
