### ISSUE TITLE
Color models

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/Markdown-Cheatsheet#6]
[color models](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#supported-color-models)

`#ffffff` 
`#000000`

**Comment by Kernix13** [comment]
What is this? What is the markdown syntax for those?

**Comment by lifeparticle** [comment]
I think it is a new feature from GitHub that works in issues, pull requests, and discussions. It seems like you just put the color code inside back-ticks

\`#ffffff\`

You can read more on this [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#supported-color-models)
